name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install cc65
      run: |
        git clone https://github.com/cc65/cc65.git
        cd cc65
        make
        make avail
    - name: Run make
      run: make
