name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install cc65
      run: sudo apt-get install cc65
    - name: Run make
      run: make
